<a href="https://colab.research.google.com/github/Laura-Neff/MissingIndicator/blob/main/MissingIndicator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.impute import MissingIndicator

In [2]:
features = [[4, 2, 1], 
            [24, 12, 6], 
            [8, 4, 2], 
            [28, 14, 7], 
            [32, 16, -1], 
            [600, 300, 150], 
            [-1, 60, 30], 
            [-1, 4, 1]]

In [3]:
indicator = MissingIndicator(missing_values=-1) #When we have a value of -1 in our array, we are saying it is missing. 

In [4]:
mask_missing_values_only = indicator.fit_transform(features)  #We are now going to make a True/False matrix to indicate where missing values are. True = missing

mask_missing_values_only

#Do you get the pattern now? When we use all these functions, we first instantiate a variable that will dictate to the next function what we want
#It will give info to the next function; if you see -1, it is a missing value
#Then, typically the "fit" and "transform" functions will take that piece of info and transform the array you give it with that info 

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [ True, False],
       [ True, False]])

In [5]:
indicator.features_ #tells us what columns are displayed; displaying only columns with missing values in this case, 0 and 2. Indexing starts at 0 

array([0, 2])

In [6]:
indicator = MissingIndicator(missing_values=-1, features="all")

In [7]:
mask_all = indicator.fit_transform(features) #A lot more clear where exactly there are missing values

mask_all

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False],
       [ True, False, False],
       [ True, False, False]])

In [8]:
indicator.features_

array([0, 1, 2])